apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://aquasecurity.github.io/helm-charts
    targetRevision: 0.24.1
    chart: trivy-operator
    helm:
      valueFiles:
      - trivy-values.yaml
      - $values/install/values-files/aws/dev/fluent-bit-aws-values.yaml
      ignoreMissingValueFiles: true
  - repoURL: 'https://github.com/cdcent/cdc-edso-platform'
    # Values from git
    ref: values
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
