loki:
  image:
    tag: latest
  enabled: true
  persistence:
     enabled: true
     accessMode:
       - ReadWriteOnce:
     size: 1Gi

fluent-bit:
  enabled: true

promtail:
  enabled: false

grafana:
  enabled: false
  persistence:
     enabled: true
     accessMode:
       - ReadWriteOnce:
     size: 1Gi
  sidecar:
    datasources:
      label: ""
      labelValue: ""
      enabled: true
      maxLines: 1000
  image:
    tag: latest

prometheus:
  enabled: false
  isDefault: false
  url: http://{{ include "prometheus.fullname" .}}:{{ .Values.prometheus.server.service.servicePort }}{{ .Values.prometheus.server.prefixURL }}
  datasource:
    jsonData: "{}"

